evaluations:
  - name: action-recognition-0001-decoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          predictions: kinetics/action-recognition-0001-encoder-predictions.pickle


        decoder:
          model:   intel/action-recognition-0001/action-recognition-0001-decoder/FP32/action-recognition-0001-decoder.xml
          weights: intel/action-recognition-0001/action-recognition-0001-decoder/FP32/action-recognition-0001-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP32

      datasets:
        - name: kinetics-400

          preprocessing:
            - type: resize
              size: 224
              aspect_ratio_scale: fit_to_window
            - type: crop
              size: 224

          metrics:
            - type: clip_accuracy
              presenter: print_vector

  - name: action-recognition-0001-decoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          predictions: kinetics/action-recognition-0001-encoder-predictions.pickle

        decoder:
          model:   intel/action-recognition-0001/action-recognition-0001-decoder/FP16/action-recognition-0001-decoder.xml
          weights: intel/action-recognition-0001/action-recognition-0001-decoder/FP16/action-recognition-0001-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
        - name: kinetics-400

          metrics:
            - type: clip_accuracy
              presenter: print_vector

global_definitions: ../dataset_definitions.yml
