models:
  - name: densenet-169-cf
    launchers:
      - framework: caffe
        model:   public/densenet-169/densenet-169.prototxt
        weights: public/densenet-169/densenet-169.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
          - type: normalization
            mean: 103.94, 116.78, 123.68
            std: 58.8235294

  - name: densenet-169
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/densenet-169/FP32/densenet-169.xml
        weights: public/densenet-169/FP32/densenet-169.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/densenet-169/FP16/densenet-169.xml
        weights: public/densenet-169/FP16/densenet-169.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
