models:
  - name: facenet-20180408-102900

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/facenet-20180408-102900/FP32/facenet-20180408-102900.xml
        weights: public/facenet-20180408-102900/FP32/facenet-20180408-102900.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   public/facenet-20180408-102900/FP16/facenet-20180408-102900.xml
        weights: public/facenet-20180408-102900/FP16/facenet-20180408-102900.bin
        adapter: reid

    datasets:
      - name: lfw

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 160
