models:
  - name: handwritten-score-recognition-0003

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/handwritten-score-recognition-0003/FP32/handwritten-score-recognition-0003.xml
        weights: intel/handwritten-score-recognition-0003/FP32/handwritten-score-recognition-0003.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/handwritten-score-recognition-0003/FP16/handwritten-score-recognition-0003.xml
        weights: intel/handwritten-score-recognition-0003/FP16/handwritten-score-recognition-0003.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

    datasets:
      - name: handwritten_score_recognition

        preprocessing:
          - type: bgr_to_gray
          - type: resize
            dst_width: 64
            dst_height: 32

        metrics:
          - type: character_recognition_accuracy
