models:
  - name: mask_rcnn_resnet101_atrous_coco

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/mask_rcnn_resnet101_atrous_coco/FP32/mask_rcnn_resnet101_atrous_coco.xml
        weights: public/mask_rcnn_resnet101_atrous_coco/FP32/mask_rcnn_resnet101_atrous_coco.bin
        adapter:
          type: mask_rcnn
          detection_out: reshape_do_2d
          raw_masks_out: masks
        cpu_extensions: AUTO
        inputs:
          - name: image_info
            type: IMAGE_INFO

      - framework: dlsdk
        tags:
          - FP16
        model:   public/mask_rcnn_resnet101_atrous_coco/FP16/mask_rcnn_resnet101_atrous_coco.xml
        weights: public/mask_rcnn_resnet101_atrous_coco/FP16/mask_rcnn_resnet101_atrous_coco.bin
        adapter:
          type: mask_rcnn
          detection_out: reshape_do_2d
          raw_masks_out: masks
        cpu_extensions: AUTO
        inputs:
          - name: image_info
            type: IMAGE_INFO

    datasets:
      - name: ms_coco_mask_rcnn_short_91_classes
        preprocessing:
          - type: resize
            size: 800
        postprocessing:
          - type: resize_prediction_boxes

        metrics:
          - type: coco_orig_segm_precision
          - type: coco_orig_precision
