models:
  - name: road-segmentation-adas-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/road-segmentation-adas-0001/FP32/road-segmentation-adas-0001.xml
        weights: intel/road-segmentation-adas-0001/FP32/road-segmentation-adas-0001.bin
        adapter: segmentation
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/road-segmentation-adas-0001/FP16/road-segmentation-adas-0001.xml
        weights: intel/road-segmentation-adas-0001/FP16/road-segmentation-adas-0001.bin
        adapter: segmentation
        cpu_extensions: AUTO

    datasets:
      - name: road_segmentation
global_definitions: ../dataset_definitions.yml
