models:
  - name: semantic-segmentation-adas-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/semantic-segmentation-adas-0001/FP32/semantic-segmentation-adas-0001.xml
        weights: intel/semantic-segmentation-adas-0001/FP32/semantic-segmentation-adas-0001.bin
        adapter: segmentation
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/semantic-segmentation-adas-0001/FP16/semantic-segmentation-adas-0001.xml
        weights: intel/semantic-segmentation-adas-0001/FP16/semantic-segmentation-adas-0001.bin
        adapter: segmentation
        cpu_extensions: AUTO

    datasets:
      - name: semantic_segmentation_adas

        metrics:
          - type: mean_iou
            use_argmax: False
            presenter: print_vector
