models:
  - name: text-recognition-0012

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP32/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP32/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        device: CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP16/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP16/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/INT8/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/INT8/text-recognition-0012.bin
        adapter: beam_search_decoder
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP32/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP32/text-recognition-0012.bin
        adapter: beam_search_decoder

      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:   Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP16/text-recognition-0012.xml
        weights: Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/dldt/FP16/text-recognition-0012.bin
        adapter: beam_search_decoder


    datasets:
      - name: ICDAR2013
        data_source: ICDAR13_REC_validation/Challenge2_Test_Task3_Images
        annotation_conversion:
          converter: icdar13_recognition
          annotation_file: ICDAR13_REC_validation/gt/gt.txt.fixed.alfanumeric

        preprocessing:
          - type: bgr_to_gray
          - type: resize
            dst_width: 120
            dst_height: 32

        metrics:
          - type: character_recognition_accuracy
