models:
  - name: text-detection-0004

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP32/text-detection-0004.xml
        weights: Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP32/text-detection-0004.bin
        adapter:
          type: text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        device: CPU
        model:   Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP16/text-detection-0004.xml
        weights: Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP16/text-detection-0004.bin
        adapter:
          type: text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/INT8/text-detection-0004.xml
        weights: Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/INT8/text-detection-0004.bin
        adapter:
          type: text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP32
        device: GPU
        model:   Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP32/text-detection-0004.xml
        weights: Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP32/text-detection-0004.bin
        adapter:
          type: text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10


      - framework: dlsdk
        tags:
          - FP16
        device: GPU
        model:  Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP16/text-detection-0004.xml
        weights: Retail/object_detection/text/pixel_link_mobilenet_v2/dldt/FP16/text-detection-0004.bin
        adapter:
          type: text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10

    datasets:
      - name: ICDAR2015

        data_source: ICDAR15_DET_validation/ch4_test_images
        annotation_conversion:
          converter: icdar15_detection
          data_dir: ICDAR15_DET_validation/gt

        preprocessing:
          - type: resize
            dst_width: 1280
            dst_height: 768

        postprocessing:
          - type: cast_to_int
          - type: filter
            area_range: 300, 980993
            height_range: 10
            width_range: 10
            apply_to: prediction
            remove_filtered: True
          - type: clip_points
            apply_to: prediction

        metrics:
          - type: text_detection
            name: f-measure
            ignore_difficult: True
