evaluations:
  - name: text-spotting-0001
    module: custom_evaluators.text_spotting_evaluator.TextSpottingEvaluator
    module_config:
      network_info:
        detector:
          model:   intel/text-spotting-0001-detector/FP32/text-spotting-0001-detector.xml
          weights: intel/text-spotting-0001-detector/FP32/text-spotting-0001-detector.bin

        recognizer_encoder:
          model:   intel/text-spotting-0001-recognizer-encoder/FP32/text-spotting-0001-recognizer-encoder.xml
          weights: intel/text-spotting-0001-recognizer-encoder/FP32/text-spotting-0001-recognizer-encoder.bin

        recognizer_decoder:
            model:   intel/text-spotting-0001-recognizer-decoder/FP32/text-spotting-0001-recognizer-decoder.xml
            weights: intel/text-spotting-0001-recognizer-decoder/FP32/text-spotting-0001-recognizer-decoder.bin

        alphabet: __0123456789abcdefghijklmnopqrstuvwxyz
        sos_index: '0'
        eos_index: '1'

        adapter:
            type: mask_rcnn_with_text
            classes_out: classes
            scores_out: scores
            boxes_out: boxes
            raw_masks_out: raw_masks
            texts_out: texts
            confidence_threshold: 0.8

      launchers:
        - framework: dlsdk
          device: CPU
          tags:
            - FP32

      datasets:
        - name: ICDAR2015_word_spotting

          preprocessing:
            - type: resize
              dst_width: 1280
              dst_height: 768

          metrics:
            - type: incidental_text_hmean
              name: f-measure
              ignore_difficult: True
              word_spotting: True

global_definitions: ../dataset_definitions.yml
